#+title: Examen de conocimiento ejemplo: Programación e ingeniería de software
#+author: Maestría en Ciencia de Datos
#+email: mcd@unison.mx
#+date: Admisión 2020-2
#+html: https://github.com/mcd-unison/prog-ejemplo
#+description: Examen ejemplo para la admisión a la /Maestria en Ciencia de Datos/ de la Universidad de Sonora
#+options: h:1 num:t toc:nil
#+LATEX_CLASS_OPTIONS: [letter,11pt]
#+LATEX_HEADER: \usepackage[spanish]{babel}

* Proyecto

 1. Ve a la [[https://github.com/mcd-unison/prog-ejemplo][pagina de =Github= del examen de ejemplo]] y realiza un =Fork= en tu cuenta propia.
 2. Clona el repositorio en tu computadora para que tengas acceso de forma local.

* Lectura y procesamiento de datos

 1. En el repositorio se encuentra el archivo =bikes.csv= el cual contiene
    información sobre la [[http://donnees.ville.montreal.qc.ca/dataset/velos-comptage][renta de bicicletas en la ciudad de Montreal]], el cual
    tiene las siguientes características:

    - El indicador de separación de columnas es el punto y coma ';', en lugar de la coma ','

    - El archivo está codificado en =latin 1= y no en =utf-8= como es habitual en los archivos modernos.

    - La columna =Date= tiene el formato =dd/mm/yyyy=.

    El archivo contiene la información de la cantidad de bicicletas que se
    retiraron de dicha estación por día (De algunas estacones no se cuenta con
    datos, o no con todos los datos).

 2. Leer el archivo (usar el lenguaje de programación de su preferencia).

 3. Graficar la cantidad de bicicletas retiradas por día para la estación ='Berri 1'=.

 4. Extraer el número de trayectos acumulados realizado por estación y por més del año.

 5. Extraer el número de trayectos promedio por estación (y de ser posible su desviación
    estandar) realizados por cada día de la semana (=lunes=, =martes=,
    =miércoles=, =jueves=, =viernes=, =sabado=, =domingo=).

 6. Guardar la información generada en un archivo tipo =json=. Documentar la
    estructura del archivo =json=.

 7. Realizar /al menos/ un =commit= con el código, el archivo =json= generado y
    la documentación del archivo. Pueden ser cuantos =commits= decidas hacer.

 8. Enviar un =pull request= a =mcd-unison= con una explicación del código realizado.

* Aspectos a evaluar

Se tomará en cuenta:

1. La calidad del código realizado.
2. La documentación del código y de los datos.
3. La solución para realizar la gráfica solicitada.
